module.exports = [
  // {
  //   slug: 'pmarca',
  //   firstName: 'Marc',
  //   lastName: 'Andreessen',
  //   twitterScreenName: 'pmarca',
  //   website: 'http://blog.pmarca.com/',
  //   picture: 'https://i.imgur.com/aoG6ED1.jpg',
  //   essayCount: 92,
  //   podcastCount: 31,
  //   tweetCount: 57,
  //   videoCount: 25,
  //   shortBio: 'Partner at a16z',
  //   bio: `Marc Andreessen is an entrepreneur, programmer, and currently a founding General Partner at Andreessen Horowitz. Marc is best known for creating the first widely used Web Browser and coining the term \'Product-Market-Fit\'. Marc has written a lot about startup advice, investing, and general technology trends.`,
  // },
  // {
  //   slug: 'balajis',
  //   twitterScreenName: 'balajis',
  //   firstName: 'Balaji',
  //   lastName: 'Srinivasan',
  //   website: 'https://balajis.com',
  //   picture: 'https://files-1wzrc11hs.now.sh',
  //   shortBio: 'Founder of Earn.com',
  //   essayCount: 11,
  //   podcastCount: 20,
  //   tweetCount: 2026,
  //   videoCount: 16,
  //   bio:
  //     'Balaji is an angel investor serial entrepreneur. He was formerly the CTO of Coinbase, and General Partner at Andreessen Horowitz and holds a BS/MS/PhD in Electrical Engineering, and an MS in Chem E. He is most active on Twitter where he covers a range of topics including crypto, politics, and startups.',
  // },
  // {
  //   slug: 'sama',
  //   twitterScreenName: 'sama',
  //   firstName: 'Sam',
  //   lastName: 'Altman',
  //   website: 'https://blog.samaltman.com/',
  //   picture: 'https://files-92487uaai.now.sh',
  //   essayCount: 96,
  //   podcastCount: 23,
  //   shortBio: 'CEO of OpenAI',
  //   tweetCount: 2836,
  //   videoCount: 28,
  //   bio:
  //     'Sam Altman is an entrepreneur, investor, programmer, and blogger. He was previously the President at Y Combinator and is now the CEO of Open AI. Sam has angel invested in many successful companies including Airbnb, Stripe, Reddit, Asana, and Pinterest. He writes about technology, and startups.',
  // },
  // {
  //   twitterScreenName: 'jesslivingston',
  //   slug: 'jesslivingston',
  //   firstName: 'Jessica',
  //   lastName: 'Livingston',
  //   website: 'http://foundersatwork.posthaven.com/',
  //   picture: 'https://i.imgur.com/52fWphv.jpg',
  //   bio:
  //     'Jessica Livingston is an entrepreneur, author, and blogger. She is the co-founder of the most influential startup accelerator in the world — Y Combinator. Jessica writes and speaks about startups, technology, and has also written a widely-read book called Founders at Work.',
  //   essayCount: 47,
  //   podcastCount: 7,
  //   shortBio: 'Founder of Y Combinator',
  //   tweetCount: 451,
  //   videoCount: 19,
  // },
  // {
  //   twitterScreenName: 'paulg',
  //   slug: 'pg',
  //   firstName: 'Paul',
  //   lastName: 'Graham',
  //   website: 'http://paulgraham.com/',
  //   picture: 'https://i.imgur.com/VLGtn32.jpg',
  //   bio:
  //     'Paul Graham is computer-scientist, entrepreneur, author, and blogger. He is the co-founder of the most influential startup accelerator in the world — Y Combinator. Paul is active on Twitter, and maintains a personal blog with many widely-read essays. He mostly writes about startups, technology, and programming languages.',
  //   essayCount: 176,
  //   podcastCount: 3,
  //   shortBio: 'Founder of Y Combinator',
  //   tweetCount: 2768,
  //   videoCount: 8,
  // },
  // {
  //   slug: 'cdixon',
  //   firstName: 'Chris',
  //   lastName: 'Dixon',
  //   twitterScreenName: 'cdixon',
  //   website: 'http://cdixon.org/',
  //   picture: 'https://i.imgur.com/NPlx6Vh.jpg',
  //   essayCount: 384,
  //   podcastCount: 20,
  //   tweetCount: 2069,
  //   videoCount: 13,
  //   shortBio: 'Partner at a16z',
  //   bio:
  //     'Chris Dixon is a General Partner at Andreessen Horowitz and focuses on cryptocurrencies. Prior to a16z, Chris was the cofounder and CEO of two startups (SiteAdvisor and Hunch). He has written extensively about technology, startup/founder advice, and  macro-trends like cryptocurrency. ',
  // },
  // {
  //   twitterScreenName: 'peterthiel',
  //   slug: 'peterthiel',
  //   firstName: 'Peter',
  //   lastName: 'Thiel',
  //   website: '',
  //   picture: 'https://i.imgur.com/7SFOvRn.jpg',
  //   essayCount: 8,
  //   podcastCount: 13,
  //   tweetCount: 1,
  //   videoCount: 33,
  //   shortBio: 'Founder of Paypal',
  //   bio:
  //     'Peter Thiel is an entrepreneur, author, and angel investor and is a founder and General Partner at Founders Fund. He made the first outside investment in Facebook, and was also a co-founder of Palantir and PayPal. His notable investments are Facebook, Linkedin, Yelp, SpaceX and Airbnb. Peter’s book Zero To One was a New York Times #1 best seller. ',
  // },
  // {
  //   twitterScreenName: 'naval',
  //   slug: 'naval',
  //   firstName: 'Naval',
  //   lastName: 'Ravikant',
  //   website: 'https://nav.al/',
  //   picture: 'https://i.imgur.com/P8Nnzf2.jpg',
  //   essayCount: 45,
  //   podcastCount: 18,
  //   tweetCount: 2712,
  //   videoCount: 22,
  //   shortBio: 'Founder of Angel List',
  //   bio:
  //     'Naval Ravikant is an entrepreneur, angel investor, and founder of AngelList. He was an early investor in companies like Twitter, Uber, Postmates, and many more. He often shares his views on Startups, Mindfulness, Crypto, and Wealth Creation on his Twitter and personal blog which have garnered a massive global audience.',
  // },
  // {
  //   slug: 'eladgil',
  //   twitterScreenName: 'eladgil',
  //   firstName: 'Elad',
  //   lastName: 'Gil',
  //   picture: 'https://files-fxw0r2skd.now.sh',
  //   website: 'http://www.eladgil.com/',
  //   bio:
  //     'Elad Gil is a serial entrepreneur, operating executive, and angel investor or advisor to private companies including AirBnB, Pinterest, Square, and Stripe. He maintains a blog where he writes extensively about startup advice, and technology trends.',
  //   essayCount: 161,
  //   podcastCount: 20,
  //   tweetCount: 2079,
  //   videoCount: 12,
  //   shortBio: 'Angel Investor',
  // },
  // {
  //   slug: 'rabois',
  //   twitterScreenName: 'rabois',
  //   firstName: 'Keith',
  //   lastName: 'Rabois',
  //   picture: 'https://files-mddkonlgh.now.sh/',
  //   website: 'https://medium.com/@rabois',
  //   essayCount: 2,
  //   podcastCount: 28,
  //   tweetCount: 3078,
  //   videoCount: 17,
  //   shortBio: 'Partner at Founders Fund',
  //   bio: '',
  // },
  // {
  //   slug: 'triketora',
  //   twitterScreenName: 'triketora',
  //   firstName: 'Tracy',
  //   lastName: 'Chou',
  //   picture: 'https://files-qylkwqehe.now.sh',
  //   website: 'https://triketora.com/',
  //   essayCount: 47,
  //   podcastCount: 11,
  //   tweetCount: 1128,
  //   videoCount: 13,
  // },
  // {
  //   slug: 'conniechan',
  //   twitterScreenName: 'conniechan',
  //   firstName: 'Connie',
  //   lastName: 'Chan',
  //   picture: 'https://files-ql94hmwfc.now.sh/',
  //   website: 'http://www.conniechan.com/',
  //   bio:
  //     "Connie Chan is a General Partner at Andressen Horowitz and focuses on consumer technology. Since joining a16z in 2011, Connie has spearheded the firm's Asia network and writes a lot about China's ever-increasing role in the global tech landscape.",
  //   essayCount: 20,
  //   podcastCount: 9,
  //   tweetCount: 511,
  //   videoCount: 5,
  //   shortBio: 'Partner at a16z',
  // },
  // {
  //   slug: 'briannekimmel',
  //   twitterScreenName: 'briannekimmel',
  //   firstName: 'Brianne',
  //   lastName: 'Kimmel',
  //   picture: 'https://files-c6m8zpzhy.now.sh',
  //   website: 'http://briannekimmel.com/',
  //   essayCount: 34,
  //   podcastCount: 10,
  //   shortBio: 'Partner at WorklifeVC',
  //   tweetCount: 3176,
  //   videoCount: 5,
  //   bio:
  //     'Brianne Kimmel is the founder and managing partner at Work Life Ventures where she makes angel/seed investments. Kimmel has invested in companies like Webflow, Tandem, and VoiceFlow.  She writes about strategies to grow your startup, tactical guides, and more generally about the current technology trends.',
  // },
  // {
  //   slug: 'stewart',
  //   twitterScreenName: 'stewart',
  //   firstName: 'Stewart',
  //   lastName: 'Butterfield',
  //   picture: 'https://files-3xzkgyjc0.now.sh',
  //   website: 'https://blog.flickr.net/author/stewartb/',
  //   bio:
  //     'Stewart Butterfield is a serial entrepreneur best known for being a co-founder of Flickr. He is now the cofounder and CEO of Slack which is one of the most widely used internal messaging applications in Silicon Valley. ',
  //   essayCount: 123,
  //   podcastCount: 19,
  //   tweetCount: 2375,
  //   videoCount: 33,
  //   shortBio: 'CEO of Slack',
  // },
  // {
  //   slug: 'bhorowitz',
  //   twitterScreenName: 'bhorowitz',
  //   firstName: 'Ben',
  //   lastName: 'Horowitz',
  //   picture: 'https://files-rb46e0u9t.now.sh/',
  //   website: 'https://medium.com/@bhorowitz',
  //   bio:
  //     'Ben Horowitz is an entrepreneur, author, and investor. He is currently a founding partner at Andreessen Horowitz along with Marc Andreessen. Prior to a16z, Ben was cofounder and CEO of Opsware which was acquired by HP for $1.6B. He was the author of a New York Times Bestseller, The Hard Thing About Hard Things.',
  //   essayCount: 133,
  //   podcastCount: 13,
  //   shortBio: 'Partner at a16z',
  //   tweetCount: 1181,
  //   videoCount: 26,
  // },
  // {
  //   podcastCount: 7,
  //   essayCount: 1,
  //   tweetCount: 660,
  //   videoCount: 9,
  //   slug: 'laurademing',
  //   twitterScreenName: 'laurademing',
  //   firstName: 'Laura',
  //   lastName: 'Deming',
  //   picture: 'https://files-oaus7870u.now.sh/',
  //   website: 'https://www.ldeming.com',
  //   shortBio: 'Partner at Longevity Fund',
  //   bio:
  //     'Laura Deming is a founding partner at Longevity Fund. Her work focuses on human life extension and using biological research to reduce the effects of aging. Deming went to MIT to study Physics, which she eventually dropped out of to become a Thiel Fellow.',
  // },
  // {
  //   podcastCount: 15,
  //   essayCount: 22,
  //   tweetCount: 2789,
  //   videoCount: 26,
  //   slug: 'mwseibel',
  //   twitterScreenName: 'mwseibel',
  //   firstName: 'Michael',
  //   lastName: 'Seibel',
  //   picture: 'https://files-be07hfaqc.now.sh/',
  //   website: 'http://www.michaelseibel.com/',
  //   shortBio: 'CEO of Y Combinator',
  //   bio:
  //     'Michael Seibel is currently the CEO of Y Combinator and was previously the co-founder and CEO Justin.tv and Socialcam. Socialcam sold to Autodesk in 2012 and under the leadership of Emmett Shear, Justin.tv became Twitch.tv and sold to Amazon in 2014. Before getting into startups, he spent a year as the finance director for a US Senate campaign and in 2005, Michael graduated from Yale University with a BA in political science.',
  // },
  // {
  //   slug: 'andrewchen',
  //   twitterScreenName: 'andrewchen',
  //   firstName: 'Andrew',
  //   lastName: 'Chen',
  //   podcastCount: 10,
  //   essayCount: 657,
  //   tweetCount: 2686,
  //   videoCount: 6,
  //   picture: 'https://files-2htnnmvse.now.sh',
  //   website: 'https://andrewchen.co/',
  //   shortBio: 'Partner at a16z',
  //   bio:
  //     'Andrew Chen is a General Partner at Andreessen Horowitz, focusing on consumer technology. Previously, he led the the Rider Growth teams at Uber. For the past decade, he’s written about mobile, metrics, and growth on his website. He is an advisor/investor for tech startups including AngelList, Barkbox, Boba Guys, Dropbox, Front, Gusto, Kiva, Product Hunt, Tinder, Workato and others. Previously, he was an Entrepreneur-in-Residence at Mohr Davidow Ventures, a Silicon Valley-based firm with $2B under management. He holds a B.S. in Applied Mathematics from the University of Washington.',
  // },
  // {
  //   slug: 'vitalikbuterin',
  //   twitterScreenName: 'vitalikButerin',
  //   firstName: 'Vitalik',
  //   lastName: 'Buterin',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://i.imgur.com/tY20fpR.jpg',
  //   website: 'https://vitalik.ca',
  //   shortBio: 'Inventor of Ethereum',
  //   bio:
  //     'Vitalik Buterin is a Russian-born computer scientist who is most known for being one of the co-founders of Ethereum and is currently one of the lead researchers at the Ethereum Foundation. Vitalik is most active on Twitter and the public Ethereum research community found at: ethresear.ch. He maintains a wideley read blog where he covers a range of topics including cryptography, economics, math and philosophy.',
  // },
  // {
  //   slug: 'marymeeker',
  //   twitterScreenName: '',
  //   firstName: 'Mary',
  //   lastName: 'Meeker',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Partner at Bond Capital',
  //   bio:
  //     'Mary Meeker is a former Wall Street securities analyst turned Venture Capitalist. She is the founder and general partner at a VC firm called Bond Capital ($1.2B fund) and was previously a partner at Kleiner Perkins where she has invested in some incredible companies including Stripe, Airbnb, Instacart, and Plaid. Mary releases a widely-read "Internet Trends Report" every year since 1995.',
  // },
  // {
  //   slug: 'alankay',
  //   twitterScreenName: 'alankay',
  //   firstName: 'Alan',
  //   lastName: 'Kay',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Computer Scientist',
  //   bio: '',
  // },
  // {
  //   slug: 'alexisohanian',
  //   twitterScreenName: 'alexisohanian',
  //   firstName: 'Alexis',
  //   lastName: 'Ohanian',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Partner at Initialized',
  //   bio: '',
  // },
  // {
  //   slug: 'annewoj23',
  //   twitterScreenName: 'annewoj23',
  //   firstName: 'Anne',
  //   lastName: 'Wojcicki',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Founder at 23andMe',
  //   bio: '',
  // },
  // {
  //   slug: 'avichal',
  //   twitterScreenName: 'avichal',
  //   firstName: 'Avichal',
  //   lastName: 'Garg',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/019d4eff-bc50-4823-a96e-e425db881fb4/avichal.jpg',
  //   website: 'https://avichal.com',
  //   shortBio: 'Partner at Electric Cap',
  //   bio:
  //     "Avichal Garg is currently a founding partner at Electric Capital. Prior to starting the fund, he was a part time partner at Y Combinator. He has invested in some incredible companies including Optimizely, Boom, Color, Cruise, Notion, Instawork, CaseText, Newfront Insurance, Threads and many more. Before being an investor Avichal started a company called Spool (acq. by Facebook) and PrepMe (acq. by The Daily Mail Group). He's most active on Twitter where he writes about crypto, startup advice, and other tech trends.",
  // },
  // {
  //   slug: 'collision',
  //   twitterScreenName: 'collision',
  //   firstName: 'John',
  //   lastName: 'Collison',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Co-Founder at Stripe',
  //   bio: '',
  // },
  // {
  //   slug: 'cyantist',
  //   twitterScreenName: 'cyantist',
  //   firstName: 'Cyan',
  //   lastName: 'Bannister',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Partner at Founders Fund',
  //   bio: '',
  // },
  // {
  //   slug: 'garrytan',
  //   twitterScreenName: 'garrytan',
  //   firstName: 'Garry',
  //   lastName: 'Tan',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Partner at Initialized',
  //   bio: '',
  // },
  // {
  //   slug: 'harris',
  //   twitterScreenName: 'harris',
  //   firstName: 'Aaron',
  //   lastName: 'Harris',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Partner at Y Combinator',
  //   bio: '',
  // },
  // {
  //   slug: 'melaniecanva',
  //   twitterScreenName: 'melaniecanva',
  //   firstName: 'Melanie',
  //   lastName: 'Perkins',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Founder at Canva',
  //   bio: '',
  // },
  // {
  //   slug: 'nickszabo4',
  //   twitterScreenName: 'nickszabo4',
  //   firstName: 'Nick',
  //   lastName: 'Szabo',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Computer Scientist',
  //   bio: '',
  // },
  // {
  //   slug: 'nolimits',
  //   twitterScreenName: 'nolimits',
  //   firstName: 'Adora',
  //   lastName: 'Cheung',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Partner at Y Combinator',
  //   bio: '',
  // },
  // {
  //   slug: 'thegothamgal',
  //   twitterScreenName: 'thegothamgal',
  //   firstName: 'Joanne',
  //   lastName: 'Wilson',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Angel Investor',
  //   bio: '',
  // },
  // {
  //   slug: 'worrydream',
  //   twitterScreenName: 'worrydream',
  //   firstName: 'Bret',
  //   lastName: 'Victor',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'Computer Scientist',
  //   bio: '',
  // },
  // {
  //   slug: 'susanwojcicki',
  //   twitterScreenName: 'susanwojcicki',
  //   firstName: 'Susan',
  //   lastName: 'Wojcicki',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/d786640f-58b6-4b88-947f-382474bd87b3/marymeeker2.jpeg',
  //   website: '',
  //   shortBio: 'CEO at YouTube',
  //   bio: '',
  // },
  // {
  //   slug: 'paultoo',
  //   twitterScreenName: 'paultoo',
  //   firstName: 'Paul',
  //   lastName: 'Bucheit',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/16d2de12-792c-4868-bd36-2386cd0be09d/paultoo.jpg',
  //   website: '',
  //   shortBio: 'Partner at YC',
  //   bio: '',
  // },
  // {
  //   slug: 'aantonop',
  //   twitterScreenName: 'aantonop',
  //   firstName: 'Andreas',
  //   lastName: 'Antonopoulos',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/5415fa8a-7d59-47b5-9a2b-1a7273fbfec3/aantonop.jpg',
  //   website: 'https://aantonop.com',
  //   shortBio: 'Computer Scientist',
  //   bio:
  //     'Andreas M. Antonopoulos is a best-selling author, speaker, educator, and one of the world’s foremost bitcoin and open blockchain experts. He is known for delivering electric talks that combine economics, psychology, technology, and game theory with current events.',
  // },
  // {
  //   slug: 'annimaniac',
  //   twitterScreenName: 'annimaniac',
  //   firstName: 'Ann',
  //   lastName: 'Miura-Ko',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/60876d02-a83f-4f04-9a6b-a7d476dc55b7/annimaniac.png',
  //   website: 'https://medium.com/@amk',
  //   shortBio: 'Partner at Floodgate',
  //   bio:
  //     'Ann Miura-Ko is an investor and co-founding partner at Floodgate. She was one of the first investors in companies such as Lyft, Refinery29 and many others. Prior to Floodgate Ann acquired a PhD at Stanford in math modeling of cybersecurity. She is active on Twitter, and as a guest on many podcasts where she discusses startups, and lessons learned as an investor.',
  // },
  // {
  //   slug: 'alexisohanian',
  //   twitterScreenName: 'alexisohanian',
  //   firstName: 'Alexis',
  //   lastName: 'Ohanian',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/06618eec-931a-47d9-aeed-f02c3a00cac0/alexisohanian.png',
  //   website: 'https://alexisohanian.com',
  //   shortBio: 'Partner at Initialized Capital',
  //   bio:
  //     "Alexis is most known for being one of the cofounders of Reddit. He was born in Brooklyn, NY and grew up in the suburbs of Baltimore, MD. He's written a national bestselling book, Without Their Permission, has long advocated for the open internet, STEM education, and paid family leave. Alongside Garry Tan, he co-founded Initialized Capital—a seed stage venture fund with over $500M under management and a portfolio with $36B in market value so far.",
  // },
  // {
  //   slug: 'patrickc',
  //   twitterScreenName: 'patrickc',
  //   firstName: 'Patrick',
  //   lastName: 'Collison',
  //   podcastCount: 0,
  //   essayCount: 0,
  //   tweetCount: 0,
  //   videoCount: 0,
  //   picture: 'https://ucarecdn.com/ce2a04f1-6046-4a87-be45-de36e1098c9e/patrickc.jpg',
  //   website: 'https://patrickcollison.com',
  //   shortBio: 'Co-Founder at Stripe',
  //   bio:
  //     'Patrick Collison is an Irish entrepreneur from County Tipperary. He is the co-founder and CEO of Stripe, which he started with his younger brother, John, in 2010. Prior to founding Stripe, Patrick and his brother John started a company called Auctomatic in 2007 which was acquired after a year by Live Current Media. ',
  // },
]
